#include "pagos/syntax/token.h"

namespace pagos::syntax {

std::string_view token_kind_name(TokenKind kind) noexcept {
    switch (kind) {
    case TokenKind::KwRecord:
        return "`record`";
    case TokenKind::Dot:
        return "`.`";
    case TokenKind::LeftBracket:
        return "`[`";
    case TokenKind::RightBracket:
        return "`]`";
    case TokenKind::End:
        return "end of file";
    case TokenKind::Identifier:
        return "identifier";
    case TokenKind::Integer:
        return "integer";
    case TokenKind::KwFn:
        return "`fn`";
    case TokenKind::KwLet:
        return "`let`";
    case TokenKind::KwStatic:
        return "`static`";
    case TokenKind::KwRuntime:
        return "`runtime`";
    case TokenKind::KwReturn:
        return "`return`";
    case TokenKind::KwIf:
        return "`if`";
    case TokenKind::KwElse:
        return "`else`";
    case TokenKind::KwFor:
        return "`for`";
    case TokenKind::KwIn:
        return "`in`";
    case TokenKind::KwTrue:
        return "`true`";
    case TokenKind::KwFalse:
        return "`false`";
    case TokenKind::KwBool:
        return "`bool`";
    case TokenKind::KwU32:
        return "`u32`";
    case TokenKind::KwU8:
        return "`u8`";
    case TokenKind::KwU16:
        return "`u16`";
    case TokenKind::KwU64:
        return "`u64`";
    case TokenKind::KwI8:
        return "`i8`";
    case TokenKind::KwI16:
        return "`i16`";
    case TokenKind::KwI32:
        return "`i32`";
    case TokenKind::KwUsize:
        return "usize";
    case TokenKind::KwI64:
        return "`i64`";
    case TokenKind::KwAs:
        return "`as`";
    case TokenKind::LeftParen:
        return "`(`";
    case TokenKind::RightParen:
        return "`)`";
    case TokenKind::LeftBrace:
        return "`{`";
    case TokenKind::RightBrace:
        return "`}`";
    case TokenKind::Colon:
        return "`:`";
    case TokenKind::Comma:
        return "`,`";
    case TokenKind::Semicolon:
        return "`;`";
    case TokenKind::Arrow:
        return "`->`";
    case TokenKind::Range:
        return "`..`";
    case TokenKind::Plus:
        return "`+`";
    case TokenKind::Minus:
        return "`-`";
    case TokenKind::Star:
        return "`*`";
    case TokenKind::Slash:
        return "`/`";
    case TokenKind::Percent:
        return "`%`";
    case TokenKind::Tilde:
        return "`~`";
    case TokenKind::Ampersand:
        return "`&`";
    case TokenKind::Pipe:
        return "`|`";
    case TokenKind::Caret:
        return "`^`";
    case TokenKind::ShiftLeft:
        return "`<<`";
    case TokenKind::ShiftRight:
        return "`>>`";
    case TokenKind::Bang:
        return "`!`";
    case TokenKind::Equal:
        return "`=`";
    case TokenKind::EqualEqual:
        return "`==`";
    case TokenKind::BangEqual:
        return "`!=`";
    case TokenKind::Less:
        return "`<`";
    case TokenKind::LessEqual:
        return "`<=`";
    case TokenKind::Greater:
        return "`>`";
    case TokenKind::GreaterEqual:
        return "`>=`";
    case TokenKind::AndAnd:
        return "`&&`";
    case TokenKind::OrOr:
        return "`||`";
    }
    return "token";
}

} // namespace pagos::syntax
